name: Buf Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Buf CLI
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Buf lint
      run: buf lint

    - name: Buf format check
      run: buf format --diff --exit-code
      continue-on-error: true

    - name: Buf breaking change detection
      run: buf breaking --against 'https://github.com/${{ github.repository }}.git#branch=main'
      if: github.ref != 'refs/heads/main'

    - name: Buf push to BSR (with git hash)
      run: buf push --tag ${{ github.sha }}
      env:
        BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
      if: github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/v')

    - name: Buf push to BSR (with version tag)
      run: buf push --tag ${GITHUB_REF#refs/tags/}
      env:
        BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/v')
